---
# tasks file for install_dependencies

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: Install build-essential
  action: apt pkg=build-essential
  become: true

- name: Install jq
  action: apt pkg=jq
  become: true
  
- name: Install git
  action: apt pkg=git
  become: true

- name: Install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: present
  when: node_type == "validator"
  become: true

