---
# tasks file for bor

- name: Cloning the Bor
  git:
    repo: "https://github.com/maticnetwork/bor.git"
    dest: "{{ ansible_env.HOME }}/bor"
    force: yes
    version: "{{ bor_branch }}"

- name: Build Bor
  command: chdir={{ ansible_env.HOME }}/bor make bor

- name: Creating symlink for bor
  file:
    src: "{{ ansible_env.HOME }}/bor/build/bin/bor"
    dest: "/usr/local/bin/bor"
    state: link
  become: true
