---
# Tasks to setup services

- name: Setup Heimdall service
  copy:
    src: "{{ ansible_env.HOME }}/heimdall/builder/files/heimdalld.service"
    dest: /lib/systemd/system/heimdalld.service
    mode: "0755"
    remote_src: true
  notify: reload heimdalld
  become: true
  tags:
    - heimdall

- name: Setup Bor service
  copy:
    src: "{{ ansible_env.HOME }}/bor/builder/files/bor.service"
    dest: /lib/systemd/system/bor.service
    mode: "0755"
    remote_src: true
  notify: reload bor
  become: true
  tags:
    - bor

- name: Create /etc/matic directory
  file:
    path: /etc/matic
    state: directory
  become: true
