---
# tasks file for heimdall

- name: install heimdall pacakges and heimdall profile
  ansible.builtin.shell:
    cmd: curl -L https://raw.githubusercontent.com/maticnetwork/install/main/heimdall.sh | bash -s -- {{ heimdall_version }} {{ network }} {{ node_type }}
